# Netlify configuration for Shah Sultan's IELTS Academy
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[context.production.environment]
  VITE_DEPLOY_ENV = "production"